create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  focus_area text not null default 'Credit Platform',
  initials text not null,
  tone text not null default 'avatar-orange',
  created_at timestamptz not null default now()
);

alter table public.team_members enable row level security;

drop policy if exists "Allow public read access to team members" on public.team_members;
drop policy if exists "Allow public insert access to team members" on public.team_members;
drop policy if exists "Allow public update access to team members" on public.team_members;
drop policy if exists "Allow public delete access to team members" on public.team_members;

create policy "Allow public read access to team members"
  on public.team_members for select
  using (true);

create policy "Allow public insert access to team members"
  on public.team_members for insert
  with check (true);

create policy "Allow public update access to team members"
  on public.team_members for update
  using (true)
  with check (true);

create policy "Allow public delete access to team members"
  on public.team_members for delete
  using (true);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null unique,
  acronym text not null,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "Allow public read access to products" on public.products;
drop policy if exists "Allow public insert access to products" on public.products;
drop policy if exists "Allow public update access to products" on public.products;
drop policy if exists "Allow public delete access to products" on public.products;

create policy "Allow public read access to products" on public.products for select using (true);
create policy "Allow public insert access to products" on public.products for insert with check (true);
create policy "Allow public update access to products" on public.products for update using (true) with check (true);
create policy "Allow public delete access to products" on public.products for delete using (true);

create table if not exists public.features (
  id bigint generated by default as identity primary key,
  name text not null,
  product text not null,
  priority text not null check (priority in ('P0', 'P1', 'P2', 'P3')),
  pm_pic_id bigint references public.team_members(id),
  qa_pic_id bigint references public.team_members(id),
  uat_start date,
  uat_end date,
  uat_status text not null default 'Planned',
  uat_signed_off date,
  uat_test_case_url text,
  uat_test_result_url text,
  live_start date,
  live_end date,
  live_status text not null default 'Planned',
  live_signed_off date,
  live_test_case_url text,
  live_test_result_url text,
  status text not null default 'planned',
  subtasks jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.features add column if not exists subtasks jsonb not null default '[]'::jsonb;
alter table public.features add column if not exists uat_test_case_url text;
alter table public.features add column if not exists uat_test_result_url text;
alter table public.features add column if not exists live_test_case_url text;
alter table public.features add column if not exists live_test_result_url text;

alter table public.features add column if not exists pm_pic_id bigint references public.team_members(id);
alter table public.features add column if not exists qa_pic_id bigint references public.team_members(id);
alter table public.features add column if not exists pm_pic_ids jsonb not null default '[]'::jsonb;
alter table public.features add column if not exists qa_pic_ids jsonb not null default '[]'::jsonb;

do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'features' and column_name = 'pm_pic') then
    update public.features feature set pm_pic_id = person.id from public.team_members person where feature.pm_pic_id is null and feature.pm_pic = person.name;
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'features' and column_name = 'qa_pic') then
    update public.features feature set qa_pic_id = person.id from public.team_members person where feature.qa_pic_id is null and feature.qa_pic = person.name;
  end if;
end $$;

alter table public.features drop column if exists pm_pic;
alter table public.features drop column if exists qa_pic;

alter table public.features enable row level security;

drop policy if exists "Allow public read access to features" on public.features;
drop policy if exists "Allow public insert access to features" on public.features;
drop policy if exists "Allow public update access to features" on public.features;
drop policy if exists "Allow public delete access to features" on public.features;

create policy "Allow public read access to features" on public.features for select using (true);
create policy "Allow public insert access to features" on public.features for insert with check (true);
create policy "Allow public update access to features" on public.features for update using (true) with check (true);
create policy "Allow public delete access to features" on public.features for delete using (true);

notify pgrst, 'reload schema';

create table if not exists public.feature_products (
  feature_id bigint not null references public.features(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (feature_id, product_id)
);

insert into public.feature_products (feature_id, product_id)
select feature.id, product.id
from public.features feature
join public.products product on lower(product.name) = lower(feature.product)
on conflict (feature_id, product_id) do nothing;

alter table public.feature_products enable row level security;

drop policy if exists "Allow public read access to feature products" on public.feature_products;
drop policy if exists "Allow public insert access to feature products" on public.feature_products;
drop policy if exists "Allow public update access to feature products" on public.feature_products;
drop policy if exists "Allow public delete access to feature products" on public.feature_products;

create policy "Allow public read access to feature products" on public.feature_products for select using (true);
create policy "Allow public insert access to feature products" on public.feature_products for insert with check (true);
create policy "Allow public update access to feature products" on public.feature_products for update using (true) with check (true);
create policy "Allow public delete access to feature products" on public.feature_products for delete using (true);