create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  focus_area text not null default 'Credit Platform',
  initials text not null,
  tone text not null default 'avatar-orange',
  created_at timestamptz not null default now()
);

alter table public.team_members enable row level security;

drop policy if exists "Allow public read access to team members" on public.team_members;
drop policy if exists "Allow public insert access to team members" on public.team_members;
drop policy if exists "Allow public update access to team members" on public.team_members;
drop policy if exists "Allow public delete access to team members" on public.team_members;

create policy "Allow public read access to team members"
  on public.team_members for select
  using (true);

create policy "Allow public insert access to team members"
  on public.team_members for insert
  with check (true);

create policy "Allow public update access to team members"
  on public.team_members for update
  using (true)
  with check (true);

create policy "Allow public delete access to team members"
  on public.team_members for delete
  using (true);

create table if not exists public.features (
  id bigint generated by default as identity primary key,
  name text not null,
  product text not null,
  priority text not null check (priority in ('P0', 'P1', 'P2', 'P3')),
  pm_pic_id bigint references public.team_members(id),
  qa_pic_id bigint references public.team_members(id),
  uat_start date,
  uat_end date,
  uat_status text not null default 'Planned',
  uat_signed_off date,
  live_start date,
  live_end date,
  live_status text not null default 'Planned',
  live_signed_off date,
  status text not null default 'planned',
  created_at timestamptz not null default now()
);

alter table public.features add column if not exists pm_pic_id bigint references public.team_members(id);
alter table public.features add column if not exists qa_pic_id bigint references public.team_members(id);

do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'features' and column_name = 'pm_pic') then
    update public.features feature set pm_pic_id = person.id from public.team_members person where feature.pm_pic_id is null and feature.pm_pic = person.name;
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'features' and column_name = 'qa_pic') then
    update public.features feature set qa_pic_id = person.id from public.team_members person where feature.qa_pic_id is null and feature.qa_pic = person.name;
  end if;
end $$;

alter table public.features drop column if exists pm_pic;
alter table public.features drop column if exists qa_pic;

alter table public.features enable row level security;

drop policy if exists "Allow public read access to features" on public.features;
drop policy if exists "Allow public insert access to features" on public.features;
drop policy if exists "Allow public update access to features" on public.features;
drop policy if exists "Allow public delete access to features" on public.features;

create policy "Allow public read access to features" on public.features for select using (true);
create policy "Allow public insert access to features" on public.features for insert with check (true);
create policy "Allow public update access to features" on public.features for update using (true) with check (true);
create policy "Allow public delete access to features" on public.features for delete using (true);

insert into public.features (name, product, priority, pm_pic_id, qa_pic_id, uat_start, uat_end, uat_status, live_start, live_end, live_status, status)
select seed.name, seed.product, seed.priority, pm.id, qa.id, seed.uat_start, seed.uat_end, seed.uat_status, seed.live_start, seed.live_end, seed.live_status, seed.status
from (values
  ('Credit limit increase', 'Credit Platform', 'P0', 'Alex Kim', 'Jamie Morgan', '2026-09-21'::date, '2026-09-25'::date, 'In progress', '2026-09-29'::date, '2026-09-30'::date, 'Planned', 'uat'),
  ('Application onboarding refresh', 'Applications', 'P1', 'Maya Lopez', 'Tessa Chen', '2026-09-28'::date, '2026-10-02'::date, 'Planned', '2026-10-07'::date, '2026-10-08'::date, 'Planned', 'planned'),
  ('Statement history export', 'Servicing', 'P2', 'Maya Lopez', 'Ravi Shah', '2026-09-14'::date, '2026-09-18'::date, 'Signed off', '2026-09-23'::date, '2026-09-24'::date, 'Planned', 'ready'),
  ('Risk band regression', 'Risk decisioning', 'P1', 'Alex Kim', 'Ravi Shah', '2026-09-15'::date, '2026-09-19'::date, 'Blocked', '2026-09-26'::date, '2026-09-27'::date, 'At risk', 'blocked')
) as seed(name, product, priority, pm_name, qa_name, uat_start, uat_end, uat_status, live_start, live_end, live_status, status)
join public.team_members pm on pm.name = seed.pm_name
join public.team_members qa on qa.name = seed.qa_name
where not exists (
  select 1 from public.features existing where existing.name = seed.name
);
