import { featureStatuses, liveStatuses, priorities, products, uatStatuses } from './config.js';

export default function FeatureModal({ feature, people, onClose, onSave }) {
  const submit = event => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const selectedPerson = fieldName => { const value = data.get(fieldName); const person = people.find(item => String(item.id) === value || item.name === value); return { id: person?.id || null, name: person?.name || value }; };
    const pm = selectedPerson('pmPic');
    const qa = selectedPerson('qaPic');
    onSave({ ...(feature || {}), name: data.get('name'), product: data.get('product'), priority: data.get('priority'), pmPicId: pm.id, pmPic: pm.name, qaPicId: qa.id, qaPic: qa.name, uatStart: data.get('uatStart'), uatEnd: data.get('uatEnd'), uatStatus: data.get('uatStatus'), uatSignedOff: data.get('uatSignedOff'), liveStart: data.get('liveStart'), liveEnd: data.get('liveEnd'), liveStatus: data.get('liveStatus'), liveSignedOff: data.get('liveSignedOff'), status: data.get('status') });
  };
  const field = (label, name, type = 'text', value = '') => <label>{label}<input name={name} type={type} defaultValue={value} /></label>;
  const personValue = (name, id) => id || name || people[0]?.id || people[0]?.name || '';
  const personOptions = people.length ? people.map(person => <option key={person.id || person.name} value={person.id || person.name}>{person.name}</option>) : <option value="">No configured members</option>;
  return <div className="modal-backdrop" onClick={event => event.target === event.currentTarget && onClose()}><div className="modal feature-modal" role="dialog" aria-modal="true" aria-labelledby="featureModalTitle"><div className="modal-header"><div><p className="eyebrow">FEATURE CONFIGURATION</p><h2 id="featureModalTitle">{feature ? 'Edit feature' : 'Add feature'}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close">×</button></div><form onSubmit={submit}><div className="form-section"><p className="form-section-title">Feature details</p>{field('Feature name', 'name', 'text', feature?.name || '')}<div className="form-row"><label>Product<select name="product" defaultValue={feature?.product || products[0]}>{products.map(product => <option key={product}>{product}</option>)}</select></label><label>Priority<select name="priority" defaultValue={feature?.priority || priorities[0]}>{priorities.map(priority => <option key={priority}>{priority}</option>)}</select></label></div><div className="form-row"><label>PM PIC<select name="pmPic" defaultValue={personValue(feature?.pmPic, feature?.pmPicId)}>{personOptions}</select></label><label>QA PIC<select name="qaPic" defaultValue={personValue(feature?.qaPic, feature?.qaPicId)}>{personOptions}</select></label></div><label>Kanban status<select name="status" defaultValue={feature?.status || featureStatuses[0].value}>{featureStatuses.map(status => <option key={status.value} value={status.value}>{status.label}</option>)}</select></label></div><div className="form-section"><p className="form-section-title">UAT testing</p><div className="form-row">{field('Start date', 'uatStart', 'date', feature?.uatStart || '')}{field('End date', 'uatEnd', 'date', feature?.uatEnd || '')}</div><div className="form-row"><label>Status<select name="uatStatus" defaultValue={feature?.uatStatus || uatStatuses[0]}>{uatStatuses.map(status => <option key={status}>{status}</option>)}</select></label>{field('Signed-off date', 'uatSignedOff', 'date', feature?.uatSignedOff || '')}</div></div><div className="form-section"><p className="form-section-title">Live testing</p><div className="form-row">{field('Start date', 'liveStart', 'date', feature?.liveStart || '')}{field('End date', 'liveEnd', 'date', feature?.liveEnd || '')}</div><div className="form-row"><label>Status<select name="liveStatus" defaultValue={feature?.liveStatus || liveStatuses[0]}>{liveStatuses.map(status => <option key={status}>{status}</option>)}</select></label>{field('Signed-off date', 'liveSignedOff', 'date', feature?.liveSignedOff || '')}</div></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button type="submit" className="primary-button">Save feature</button></div></form></div></div>;
}
